# Generated by Django 5.2.1 on 2025-06-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('subjects', '0002_alter_subject_options_remove_subject_semester_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['date', 'name']},
        ),
        migrations.RenameField(
            model_name='assessment',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='due_date',
        ),
        migrations.AddField(
            model_name='assessment',
            name='date',
            field=models.DateField(blank=True, help_text='Date of the assessment', null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='subjects.subject'),
        ),
    ]
