# Generated by Django 5.2.1 on 2025-06-03 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subject_options_remove_subject_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Weight for activities (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('quiz_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Weight for quizzes (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_weight', models.DecimalField(decimal_places=2, default=40.0, help_text='Weight for exams (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grade_weights', to='subjects.subject')),
            ],
        ),
    ]
