# Generated by Django 5.2.1 on 2025-06-03 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['year_level', 'name']},
        ),
    ]
